# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "jasmine.psaris.com"
name: "jasmine.psaris.com"
url: "https://jasmine.psaris.com"
#logo: "/assets/images/vecsig.png"
email: "jasmine@psaris.com"
description: >- # this means to ignore newlines until next line without indents
  Jasmine Psaris was born in New York City and spent her childhood in Hong Kong.
  She attended Hong Kong International School (HKIS) through 6th grade.
  Jasmine was diagnosed with Osteosarcoma in 2014 and received treatment at Queen Mary Hospital in Hong Kong and
  Memorial Sloan Kettering Cancer Center in New York.  She passed away on November 27 2017,
  shortly after her 13th birthday.
github_username: jahzee
minimal_mistakes_skin: air
#search: true
#search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - "*.org"
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

analytics:
  provider: "google"
  google:
    tracking_id: "UA-177360111-2"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jasmine Psaris"
  avatar : "/assets/images/jasmine.jpg"
  bio    : "Lover of Cats, Minecraft and Art"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jasmine.psaris.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jasminepsaris/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jahzee"
    - label: "Amazon"
      icon: "fab fa-fw fa-amazon"
      url: "https://www.amazon.com/Jasmine-L-Psaris/e/B08QZSMPXN"
      

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jasminepsaris/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jahzee"
    - label: "Amazon"
      icon: "fab fa-fw fa-amazon"
      url: "https://www.amazon.com/Jasmine-L-Psaris/e/B08QZSMPXN"

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      header:
        overlay_image: /assets/images/trixie.jpg
        overlay_filter: 0.3 # same as adding an opacity of 0.5 to a black background
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      toc_label: Contents
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      
# Collections
collections:
  paintBook:
    output: true

  pictureBook:
    output: true

  storyBook:
    output: true

  sketches:
    output: true

  galleries:
    output: true
    permalink: /:collection/:path/

imagesurl: "/assets/images/"
   
